#!/bin/sh

#udiskie &

# Set background image with feh
feh --bg-scale /home/orka/Pictures/Wallpapers/wallpaper.jpg &
#~/bin/wm/init-wallpaper &

#xkbcomp -I$HOME/.xkb $HOME/.keymap.xkb $DISPLAY

export SUDO_ASKPASS=ssh-askpass

urxvt -e ranger
