#!/bin/sh

udiskie &

ibus-daemon -drx
#synergy &
xkbcomp -I$HOME/.xkb $HOME/.keymap.xkb $DISPLAY
# Set background image with feh
feh --bg-scale /home/orka/Pictures/Wallpapers/milky-way-clipart-1080p-3.jpg &
~/bin/wm/init-wallpaper &

#source (xkbcomp -I$HOME/.xkb $HOME/.keymap.xkb $DISPLAY)
xkbcomp ~/.config/xkb.dump $DISPLAY



urxvt -e ranger
