def plug -params 1 %{
  %sh{
    if [ ! -d $HOME/build/$1 ]; then
      (cd $HOME/build; git clone https://github.com/$1 2> /dev/null)
    fi
    for file in $(echo $HOME/build/$(basename $1)/*.kak); do
      echo source "$file"
    done
  }
}

plug occivink/kakoune-vertical-selection
plug occivink/kakoune-interactive-itersel
plug occivink/kakoune-expand
plug occivink/kakoune-find
plug occivink/kakoune-sudo-write
plug danr/kakoune-easymotion
plug fsub/kakoune-mark



#hook global WinCreate .* %{addhl window/ number_lines}
hook global WinCreate .* %{addhl window/ show_whitespaces}  

hook global WinCreate .* %{set global indentwidth 2}
hook global WinCreate .* %{set global tabstop 2}
hook global WinCreate .* %{hook window InsertChar \t %{ exec -draft h@}}

#hook global InsertChar \( 'exec )<left>'
#hook global InsertChar \{ 'exec }<left>'
#hook global InsertChar \[ 'exec ]<left>'
#hook global InsertChar \< 'exec ><left>'
#hook global InsertChar ' "exec '<left>"


hook global WinCreate .* %{ addhl window/ show_matching }

#hook global BufCreate .* %{editorconfig-load}
hook global BufCreate .vue %{ set buffer filetype xml }
hook global BufCreate .*.elm %{ set buffer filetype haskell }
hook global BufCreate .*.purs %{ set buffer filetype haskell }
hook global BufCreate .*.(es6|tsx?) %{ set buffer filetype javascript }

hook global WinSetOption filetype=(c|cpp|cc|h|hpp) %{
    clang-enable-autocomplete 
    clang-enable-diagnostics
    alias window lint clang-parse
    alias window lint-next clang-diagnostics-next
    %sh{
        if [ $PWD = "/home/mawww/prj/kakoune/src" ]; then
           echo "set buffer clang_options '-std=c++14 -include-pch precomp-header.h.gch -DKAK_DEBUG'"
        fi
    }
    #ycmd-enable-autocomplete
}

hook global WinSetOption filetype=python %{
    jedi-enable-autocomplete
    flake8-enable-diagnostics
    alias window lint flake8-lint
    alias window lint-next flake8-diagnostics-next
    %sh{
        if [ $PWD = "/home/mawww/prj/kakoune/src" ]; then
           echo "set buffer jedi_python_path '/usr/share/gdb/python'"
           echo "set buffer path './:/usr/share/gdb/python'"
        fi
    }
}

decl -hidden regex curword
face CurWord default,rgb:4a4a4a

hook global WinCreate .* %{
    addhl global/ show_matching
    addhl global/ dynregex '%reg{/}' 0:+u 

    # Highlight the word under the cursor
    addhl global/ dynregex '%opt{curword}' 0:CurWord
}

hook global NormalIdle .* %{
    eval -draft %{ try %{
        exec <space><a-i>w <a-k>\`\w+\'<ret>
        set buffer curword "\b\Q%val{selection}\E\b"
    } catch %{
        set buffer curword ''
    } }
}
hook global BufOpenFifo '\*grep\*' %{ map -- global normal - ':grep-next<ret>' }
hook global BufOpenFifo '\*make\*' %{ map -- global normal - ':make-next<ret>' }

hook global WinCreate ^[^*]+$ %{ addhl global/ number_lines }

#set global ycmd_path /home/mawww/prj/ycmd/ycmd/

def ide %{
    rename-client main
    set global jumpclient main

    new rename-client tools
    set global toolsclient tools

    new rename-client docs
    set global docsclient docs
}

hook global InsertCompletionShow .* %{ map window insert <tab> <c-n>; map window insert <backtab> <c-p> }
hook global InsertCompletionHide .* %{ unmap window insert <tab> <c-n>; unmap window insert <backtab> <c-p> }

hook global InsertChar k %{ try %{
    exec -draft hH <a-k>jk<ret> d
    exec <esc>
}}

#def find -params 1 -shell-candidates %{ find . -type f } %{ edit %arg{1} }


# set global autoinfo 2

set global ui_options ncurses_status_on_top=true
set global tabstop     4
set global indentwidth 4
set global scrolloff 1,5
#set global makecmd 'make --jobs=8'
#set global grepcmd 'ag --filename --column'

#set global makecmd 'make -j8'
#set global grepcmd 'rg --vimgrep --colors \'match:fg:magenta\' --colors \'line:bg:yellow\' '
set global grepcmd 'rg --vimgrep -s -p'
map global normal <c-p> :lint<ret>


map global normal '#' :comment-line<ret>
map global normal = ':prompt math: %{exec "a%val{text}<lt>esc>|bc<lt>ret>"}<ret>'

map global user n ':lint-next<ret>'
map global user p '!xclip -o<ret>'
map global user y '<a-|>xclip -i<ret>; :echo -color Information "copied selection to X11 clipboard"<ret>'
map global user R '|xclip -o<ret>'



# copy to clipboar
#hook global NormalKey y|d|c %{ nop %sh{
#  printf %s "$kak_reg_dquote" | xsel --input --clipboard
#}}

# paste from clipboard
#map global user P '!xsel --output --clipboard<ret>'
#map global user p '<a-!>xsel --output --clipboard<ret>'


map -docstring 'case insensitive search' global user '/' /(?i)
map -docstring 'case insensitive backward search' global user '<a-/>' <a-/>(?i)
map -docstring 'case insensitive extend search' global user '?' ?(?i)
map -docstring 'case insensitive backward extend-search' global user '<a-?>' <a-?>(?i)

#colorscheme desertex

## User keys

# vim old habits
map global normal D '<a-l>d' -docstring 'delete to end of line'
map global normal Y '<a-l>y' -docstring 'yank to end of line'
map global normal '#' :comment-line<ret> -docstring 'comment line'
map global normal '<a-#>' :comment-block<ret> -docstring 'comment block'
map global goto m '<esc>m;' -docstring 'matching char'

# alias
#alias global tv tmux-repl-vertical
#alias global th tmux-repl-vertical
# Option
map global normal <space> ,
map global normal  , <space>


map global user <space> ':fzf-file<ret>'
map global user f ':fzf-buffer<ret>'
#map global user t ':fzf <ret>'
map global user / 'wb*'

map global user d 'wb:ctags-search<ret>'
