#def plug -params 1 %{
#  %sh{
#    if [ ! -d $HOME/build/$1 ]; then
#      (cd $HOME/build; git clone https://github.com/$1 2> /dev/null)
#    fi
#    for file in $(echo $HOME/build/$(basename $1)/*.kak); do
#      echo source "$file"
#    done
#  }
#}

# Plugins

source "%val{config}/plugins/plug.kak/rc/plug.kak"

plug "andreyorst/plug.kak" noload
plug occivink/kakoune-vertical-selection
plug occivink/kakoune-interactive-itersel
plug occivink/kakoune-expand
plug occivink/kakoune-find
plug occivink/kakoune-sudo-write
plug danr/kakoune-easymotion
plug fsub/kakoune-mark
plug Delapouite/kakoune-buffers
plug "andreyorst/powerline.kak"
plug "lenormf/kakoune-extra" %{

    ##VCS
    declare-option str-list ctagsfiles

    hook global BufCreate .* %{
        %sh{
            if [ -e "${kak_opt_vcs_root_path}/tags" ]; then
                printf 'set-option -add buffer ctagsfiles %%{%s}\n' "${kak_opt_vcs_root_path}/tags"
                #printf 'declare-option -add buffer ctagsfiles %%{%s}\n' "${kak_opt_vcs_root_path}/tags"
            fi
        }
        #declare-option -add buffer ctagsfiles %%{%s}\n' "${kak_opt_vcs_root_path}/tags
    }

    hook global WinCreate .* %{ evaluate-commands %sh{
        if [ -n "${kak_opt_vcs_root_path}" ]; then
            case "${kak_opt_vcs_name}" in
                git)
                    echo "
                        git show-diff
                        hook global BufWritePost %val{buffile} %{git update-diff}
                        hook global BufReload %val{buffile} %{git update-diff}
                        hook global WinDisplay %val{buffile} %{git update-diff}
                    ";;
            esac
        fi
    } }
}


plug "andreyorst/fzf.kak" %{

map global user f -docstring 'Open fzf mode' %{: fzf-mode<ret>}
#map global fzf g -docstring 'Open vcs mode' %{: fzf-vcs-mode<ret>}
#map global fzf b -docstring 'Open fzf-buffer mode' ':fzf-buffer<ret>'
map global fzf f -docstring 'fzf file mode' ':fzf-file<ret>'
#map global fzf t -docstring 'Open fzf' ':fzf <ret>'

#source "%val{config}/plugins/fzf.kak/rc/fzf-modules/fzf-file.kak"   # fzf file chooser
#source "%val{config}/plugins/fzf.kak/rc/fzf-modules/fzf-buffer.kak" # switching buffers with fzf
#source "%val{config}/plugins/fzf.kak/rc/fzf-modules/fzf-search.kak" # search within file contents
#source "%val{config}/plugins/fzf.kak/rc/fzf-modules/fzf-cd.kak"     # change server's working directory
#source "%val{config}/plugins/fzf.kak/rc/fzf-modules/fzf-ctags.kak"  # search for tag in your project ctags file
#source "%val{config}/plugins/fzf.kak/rc/fzf-modules/fzf-git.kak"    # git support modulemap global user f -docstring 'Open fzf mode' %{: fzf-mode<ret>}
}

plug "andreyorst/tagbar.kak" config %{
    # if you have wrap highlighter enamled in you configuration
    # files it's better to turn it off for tagbar, using this hook:
    hook global WinSetOption filetype=tagbar %{
        remove-highlighter window/wrap
        # you can also disable rendering whitespaces here, and
    }
}


plug "occivink/kakoune-phantom-selection" %{
    declare-user-mode phantom-selection
    map global user h -docstring "Phantom selections" ": enter-user-mode phantom-selection<ret>"
    map global phantom-selection n -docstring "Next" ": phantom-sel-iterate-next<ret>"
    map global phantom-selection p -docstring "Previous" ": phantom-sel-iterate-prev<ret>"
    map global phantom-selection c -docstring "Clear" ": phantom-sel-select-all; phantom-sel-clear<ret>"
    map global phantom-selection a -docstring "Add" ": phantom-sel-add-selection<ret>"
}
plug "occivink/kakoune-snippets" %{
    set-option global snippets_auto_expand true
    declare-user-mode snippets
    map global user s -docstring "Snippets" ": enter-user-mode snippets<ret>"
    map global snippets n -docstring "Select next placeholder" ": snippets-select-next-placeholders<ret>"
    map global snippets s -docstring "Snippet" ": snippets "
    map global snippets i -docstring "Info" ": snippets-info<ret>"
    map global insert <a-e> "<esc>: try snippets-select-next-placeholders catch phantom-sel-iterate-next<ret>i"
    add-highlighter global/ ranges snippets_placeholders
    source "%val{config}/snippets.kak"
}

plug "occivink/kakoune-sudo-write"
plug "jjk96/kakoune-fireplace"
plug "lenormf/kakoune-extra" load %{
    syntastic.kak
}
plug "alexherbo2/yank-ring.kak" %{
    map global normal <c-p> ':<space>yank-ring<ret><c-p>'
    map global normal <c-n> ':<space>yank-ring<ret><c-n>'
}
plug "Delapouite/kakoune-buffers" %{
    map global user b ': enter-user-mode -lock buffers<ret>'   -docstring 'buffers (lock)…'
}
plug "ul/kak-tree" %{
    declare-user-mode tree
    map global tree u ': tree-select-parent-node<ret>' -docstring 'parent'
    map global tree n ': tree-select-next-node<ret>' -docstring 'next'
    map global tree p ': tree-select-previous-node<ret>' -docstring 'previous'
    map global tree c ': tree-select-children<ret>' -docstring 'children'
    map global tree f ': tree-select-first-child<ret>' -docstring 'first child'
    map global tree t ': tree-node-sexp<ret>' -docstring 'show syntax tree'
    map global tree . ': enter-user-mode -lock tree<ret>' -docstring 'lock'
    map global user t ': enter-user-mode tree<ret>' -docstring 'tree-sitter'
}
plug 'delapouite/kakoune-cd' %{
    # Suggested aliases
    alias global cdb change-directory-current-buffer
    alias global cdr change-directory-project-root
    alias global ecd edit-current-buffer-directory
    alias global pwd print-working-directory
}
plug 'Delapouite/kakoune-mirror' %{
    map global user o -docstring 'mirror' ': enter-user-mode mirror<ret>'
    map global mirror * -docstring 'stars (markdown bold)' 'i**<esc>a**<esc>'
    map global mirror . ': enter-user-mode -lock mirror<ret>'
}


hook global WinCreate .* %{addhl window/ show_whitespaces}

hook global WinCreate .* %{set global indentwidth 4}
hook global WinCreate .* %{set global tabstop 4}
hook global WinCreate .* %{hook window InsertChar \t %{ exec -draft h@}}

#hook global InsertChar \( 'exec )<left>'
#hook global InsertChar \{ 'exec }<left>'
#hook global InsertChar \[ 'exec ]<left>'
#hook global InsertChar \< 'exec ><left>'
#hook global InsertChar ' "exec '<left>"


hook global WinCreate .* %{ addhl window/ show_matching }

#hook global BufCreate .* %{editorconfig-load}
hook global BufCreate .vue %{ set buffer filetype xml }
hook global BufCreate .*.elm %{ set buffer filetype haskell }
hook global BufCreate .*.purs %{ set buffer filetype haskell }
hook global BufCreate .*.(es6|tsx?) %{ set buffer filetype javascript }

hook global WinSetOption filetype=(c|cpp|cc|h|hpp) %{
    clang-enable-autocomplete
    clang-enable-diagnostics
    alias window lint clang-parse
    alias window lint-next clang-diagnostics-next
    %sh{
        if [ $PWD = "/home/mawww/prj/kakoune/src" ]; then
           echo "set buffer clang_options '-std=c++14 -include-pch precomp-header.h.gch -DKAK_DEBUG'"
        fi
    }
    #ycmd-enable-autocomplete
}

hook global WinSetOption filetype=python %{
    jedi-enable-autocomplete
    flake8-enable-diagnostics
    alias window lint flake8-lint
    alias window lint-next flake8-diagnostics-next
    %sh{
        if [ $PWD = "/home/mawww/prj/kakoune/src" ]; then
           echo "set buffer jedi_python_path '/usr/share/gdb/python'"
           echo "set buffer path './:/usr/share/gdb/python'"
        fi
    }
}

decl -hidden regex curword
face global CurWord default,rgb:4a4a4a

hook global WinCreate .* %{
    addhl global/ show_matching
    addhl global/ dynregex '%reg{/}' 0:+u

    # Highlight the word under the cursor
    addhl global/ dynregex '%opt{curword}' 0:CurWord
}

hook global NormalIdle .* %{
    eval -draft %{ try %{
        exec <space><a-i>w <a-k>\`\w+\'<ret>
        set buffer curword "\b\Q%val{selection}\E\b"
    } catch %{
        set buffer curword ''
    } }
}
hook global BufOpenFifo '\*grep\*' %{ map -- global normal - ':grep-next<ret>' }
hook global BufOpenFifo '\*make\*' %{ map -- global normal - ':make-next<ret>' }

hook global WinCreate ^[^*]+$ %{ addhl global/ number_lines }

#set global ycmd_path /home/mawww/prj/ycmd/ycmd/

def ide %{
    rename-client main
    set global jumpclient main

    new rename-client tools
    set global toolsclient tools

    new rename-client docs
    set global docsclient docs
}

#hook global InsertCompletionShow .* %{ map window insert <tab> <c-n>; map window insert <backtab> <c-p> }
#hook global InsertCompletionHide .* %{ unmap window insert <tab> <c-n>; unmap window insert <backtab> <c-p> }

hook global InsertChar k %{ try %{
    exec -draft hH <a-k>jk<ret> d
    exec <esc>
}}

#def find -params 1 -shell-candidates %{ find . -type f } %{ edit %arg{1} }


# set global autoinfo 2

set global ui_options ncurses_status_on_top=true
set global tabstop     4
set global indentwidth 4
set global scrolloff 1,5
#set global makecmd 'make --jobs=8'
#set global grepcmd 'ag --filename --column'

#set global makecmd 'make -j8'
#set global grepcmd 'rg --vimgrep --colors \'match:fg:magenta\' --colors \'line:bg:yellow\' '
#set global grepcmd 'rg --vimgrep -s -p'
#map global normal <c-p> :lint<ret>


map global normal '#' :comment-line<ret>
map global normal = ':prompt math: %{exec "a%val{text}<lt>esc>|bc<lt>ret>"}<ret>'

#map global user n ':lint-next<ret>'
map global user p '!xclip -o<ret>'
map global user y '<a-|>xclip -i<ret>; :echo -color Information "copied selection to X11 clipboard"<ret>'
map global user R '|xclip -o<ret>'



# copy to clipboar
#hook global NormalKey y|d|c %{ nop %sh{
#  printf %s "$kak_reg_dquote" | xsel --input --clipboard
#}}

# paste from clipboard
#map global user P '!xsel --output --clipboard<ret>'
#map global user p '<a-!>xsel --output --clipboard<ret>'


map -docstring 'case insensitive search' global user '/' /(?i)
map -docstring 'case insensitive backward search' global user '<a-/>' <a-/>(?i)
map -docstring 'case insensitive extend search' global user '?' ?(?i)
map -docstring 'case insensitive backward extend-search' global user '<a-?>' <a-?>(?i)

#colorscheme desertex

## User keys

# vim old habits
map global normal D '<a-l>d' -docstring 'delete to end of line'
map global normal Y '<a-l>y' -docstring 'yank to end of line'
map global normal '#' :comment-line<ret> -docstring 'comment line'
map global normal '<a-#>' :comment-block<ret> -docstring 'comment block'
map global goto m '<esc>m;' -docstring 'matching char'

# alias
#alias global tv tmux-repl-vertical
#alias global th tmux-repl-vertical
# Option
map global normal <space> ,
map global normal  , <space>



map global user / 'wb*'
hook global BufWritePre .* %{exec -draft '%s\h+$<ret>d'}

map global user d 'wb:ctags-search<ret>'

# Overwrites colors defined in kak-lsp
#colorscheme gruvbox

# CLI utils
##
def suspend-and-resume \
    -params 1..2 \
    -docstring 'suspend-and-resume <cli command> [<kak command after resume>]: backgrounds current kakoune client and runs specified cli command.  Upon exit of command the optional kak command is executed.' \
    %{ evaluate-commands %sh{

    # Note we are adding '&& fg' which resumes the kakoune client process after the cli command exits
    cli_cmd="$1 && fg"
    post_resume_cmd="$2"

    # automation is different platform to platform
    platform=$(uname -s)
    case $platform in
        Darwin)
            automate_cmd="sleep 0.01; osascript -e 'tell application \"System Events\" to keystroke \"$cli_cmd\\n\" '"
            kill_cmd="/bin/kill"
            break
            ;;
        Linux)
            automate_cmd="sleep 0.2; xdotool type '$cli_cmd'; xdotool key Return"
            kill_cmd="/usr/bin/kill"
            break
            ;;
    esac

    # Uses platforms automation to schedule the typing of our cli command
    nohup sh -c "$automate_cmd"  > /dev/null 2>&1 &
    # Send kakoune client to the background
    $kill_cmd -SIGTSTP $kak_client_pid

    # ...At this point the kakoune client is paused until the " && fg " gets run in the $automate_cmd

    # Upon resume, run the kak command is specified
    if [ ! -z "$post_resume_cmd" ]; then
        echo "$post_resume_cmd"
    fi
}}

##
def tig-blame -override -docstring 'Open blame in tig for current file and line' %{
    # Note here we aren't passing any command on resume of kakoune
    suspend-and-resume "tig blame +%val{cursor_line} %val{buffile}"
}

declare-user-mode tig
map global tig b ': tig-blame<ret>' -docstring 'show blame (with tig)'
map global tig s ': suspend-and-resume "tig status"<ret>' -docstring 'show git status (with tig)'
map global tig m ': suspend-and-resume "tig"<ret>' -docstring 'show main view (with tig)'

map global user t ': enter-user-mode tig<ret>' -docstring 'tig commands'

## ranger
def for-each-line \
    -docstring "for-each-line <command> <path to file>: run command with the value of each line in the file" \
    -params 2 \
    %{ evaluate-commands %sh{

    while read f; do
        printf "$1 $f\n"
    done < "$2"
}}

def toggle-ranger %{
    suspend-and-resume \
        "ranger --choosefiles=/tmp/ranger-files-%val{client_pid}" \
        "for-each-line edit /tmp/ranger-files-%val{client_pid}"
}

map global user r ': toggle-ranger<ret>' -docstring 'select files in ranger'

define-command symbol -params 1 -shell-script-candidates %{
    tags="${TMPDIR:-/tmp}/tags-${kak_buffile##*/}"; tags="${tags%.*}"
    ctags -f $tags $kak_buffile
    readtags -t $tags -l | cut -f 1 | awk '!x[$0]++' | grep -v -e "__anon.*"
    } %{ evaluate-commands %sh{
    tags="${TMPDIR:-/tmp}/tags-${kak_buffile##*/}"; tags="${tags%.*}"
    readtags -t $tags $1 | awk -F '\t|\n' '
        /^!TAGROOT\t/ { tagroot=$2 }
        /[^\t]+\t[^\t]+\t\/\^.*\$?\// {
            re=$0;
            sub(".*\t/\\^", "", re); sub("\\$?/$", "", re); gsub("(\\{|\\}|\\\\E).*$", "", re);
            keys=re; gsub(/</, "<lt>", keys); gsub(/\t/, "<c-v><c-i>", keys);
            out = out " %{" $2 " {MenuInfo}" re "} %{evaluate-commands %{ try %{ edit %{" tagroot $2 "}; execute-keys %{/\\Q" keys "<ret>vc} } catch %{ echo %{unable to find tag} } } }"
        }
        /[^\t]+\t[^\t]+\t[0-9]+/ { out = out " %{" $2 ":" $3 "} %{evaluate-commands %{ edit %{" tagroot $2 "} %{" $3 "}}}" }
        END { print ( length(out) == 0 ? "echo -markup %{{Error}no such tag " ENVIRON["tagname"] "}" : "menu -markup -auto-single " out ) }'
    rm $tags
}}
