#!/bin/sh

udiskie &

# Set background image with feh
#feh --bg-scale /usr/share/wallpapers/Autumn/contents/images/1920x1080.jpg &
feh --bg-scale /usr/share/wallpapers/Bamboo/contents/images/5120x2880.png &

deadd-notification-center &

~/.xmonad/bin/autolock

barrier

# urxvt -e ranger
