#!/bin/sh

udiskie &

# Set background image with feh
feh --bg-scale /usr/share/wallpapers/Autumn/contents/images/1920x1080.jpg &
~/bin/wm/init-wallpaper &
deadd-notification-center

# urxvt -e ranger
