
# A continuation prompt that displays two filled in arrows
continuation_prompt = '▶▶ '

format = """
[](#000000)\
$os\
$username\
[](bg:#171717 fg:#000000)\
$directory\
[](fg:#171717 bg:#FCA17D)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#86BBD8)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$kotlin\
$scala\
$zig\
[](fg:#86BBD8 bg:#06969A)\
$docker_context\
[](fg:#76963A bg:#2D2A2C)\
$memory_usage\
[](fg:#2D2A2C bg:#000000)\
$time\
[ ](fg:#000000)\
\n$character"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#000000 fg:#757575"
style_root = "bg:#800000 fg:#757575"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#000000"
disabled = true # Disabled by default

[directory]
style = "bg:#171717 fg:#757575"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A fg:#252525"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#FCA17D fg:#252525"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#FCA17D fg:#252525"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[kotlin]
symbol = '🅺 '
kotlin_binary = 'kotlinc'
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[zig]
symbol = '⚡️ '
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[memory_usage]
disabled = false
threshold = -1
symbol = '󰈙'
style = "bg:#2D2A2C fg:#757575"
format = '[ $symbol $ram:$ram_pct ]($style)'

[time]
disabled = false
time_format = "%r" # Hour:Minute Format
style = "bg:#000000 fg:#757575"
format = '[ ♥ $time ]($style)'
